export type UserRole = 'superuser' | 'supervisor' | 'admin' | 'user' | 'reviewer';

export interface CIO {
  id: string;
  name: string;
  platform: string;
}

export interface UserProfile {
  name: string;
  role: UserRole;
  cioId?: string; // for supervisors, which CIO they are
  platformId?: string; // for user/TPL role, assigned platform
}

export interface ActionItem {
  id: string;
  pillar: string;
  platform: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  status: 'open' | 'in_progress' | 'done';
  createdBy: string;
  isAutoGenerated: boolean;
}

export interface TeamData {
  name: string;
  maturity: number;
  performance: number;
  agility: number;
  stability: number;
  platform: string;
  subPlatform: string;
  pillar: string;
  quarter: string;
}

export interface DimensionScore {
  name: string;
  weight: number;
  scores: number[];
  average: number;
}

export interface TimeSeriesPoint {
  period: string;
  maturity: number;
  performance: number;
  agility: number;
}

export interface QuarterlyTrend {
  quarter: string;
  stability: number;
  maturity: number;
  performance: number;
  agility: number;
  weightedAverage: number;
}

export interface AppState {
  user: UserProfile | null;
  setUser: (user: UserProfile | null) => void;
  role: UserRole;
  setRole: (role: UserRole) => void;
  teams: TeamData[];
  setTeams: (teams: TeamData[]) => void;
  platforms: string[];
  setPlatforms: (p: string[]) => void;
  pillars: string[];
  setPillars: (p: string[]) => void;
  cios: CIO[];
  maturityDimensions: DimensionScore[];
  performanceMetrics: DimensionScore[];
  timeSeries: TimeSeriesPoint[];
  setTimeSeries: (ts: TimeSeriesPoint[]) => void;
  selectedPlatform: string;
  setSelectedPlatform: (p: string) => void;
  selectedPillar: string;
  setSelectedPillar: (p: string) => void;
  selectedQuarter: string;
  setSelectedQuarter: (q: string) => void;
  quarterlyTrends: QuarterlyTrend[];
  availableQuarters: string[];
}
