import React, { useState, useMemo } from 'react';
import { useAppState } from '@/context/AppContext';
import { ActionItem } from '@/types/maturity';
import { Plus, Lightbulb, CheckCircle2, Clock, AlertTriangle, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import ChartChatBox from '@/components/ChartChatBox';

interface ActionItemsProps {
  platformFilter?: string;
}

const ActionItems: React.FC<ActionItemsProps> = ({ platformFilter }) => {
  const { teams, selectedQuarter, pillars, platforms } = useAppState();
  const [manualItems, setManualItems] = useState<ActionItem[]>([]);
  const [showAddForm, setShowAddForm] = useState(false);
  const [newDesc, setNewDesc] = useState('');
  const [newPillar, setNewPillar] = useState('');
  const [newPlatform, setNewPlatform] = useState(platformFilter ?? '');
  const [newPriority, setNewPriority] = useState<'high' | 'medium' | 'low'>('medium');

  const relevantPlatforms = platformFilter ? [platformFilter] : platforms;

  // Auto-generate suggestions based on low-scoring areas
  const autoSuggestions = useMemo(() => {
    const suggestions: ActionItem[] = [];
    const currentTeams = teams.filter(t => t.quarter === selectedQuarter);

    relevantPlatforms.forEach(platform => {
      pillars.forEach(pillar => {
        const pTeams = currentTeams.filter(t => t.platform === platform && t.pillar === pillar);
        if (pTeams.length === 0) return;

        const avgMaturity = pTeams.reduce((s, t) => s + t.maturity, 0) / pTeams.length;
        const avgPerformance = pTeams.reduce((s, t) => s + t.performance, 0) / pTeams.length;
        const avgAgility = pTeams.reduce((s, t) => s + t.agility, 0) / pTeams.length;
        const avgStability = pTeams.reduce((s, t) => s + t.stability, 0) / pTeams.length;

        if (avgMaturity < 5) {
          suggestions.push({
            id: `auto-mat-${platform}-${pillar}`,
            pillar, platform,
            description: `Maturity score is low (${avgMaturity.toFixed(1)}/10). Focus on improving foundational practices in ${pillar}.`,
            priority: avgMaturity < 3 ? 'high' : 'medium',
            status: 'open',
            createdBy: 'System',
            isAutoGenerated: true,
          });
        }
        if (avgPerformance < 5) {
          suggestions.push({
            id: `auto-perf-${platform}-${pillar}`,
            pillar, platform,
            description: `Performance score is low (${avgPerformance.toFixed(1)}/10). Review throughput and deployment metrics in ${pillar}.`,
            priority: avgPerformance < 3 ? 'high' : 'medium',
            status: 'open',
            createdBy: 'System',
            isAutoGenerated: true,
          });
        }
        if (avgAgility < 4.5) {
          suggestions.push({
            id: `auto-agi-${platform}-${pillar}`,
            pillar, platform,
            description: `Agility index is below target (${avgAgility.toFixed(1)}/10). Consider agile coaching for ${pillar} teams.`,
            priority: avgAgility < 3 ? 'high' : 'medium',
            status: 'open',
            createdBy: 'System',
            isAutoGenerated: true,
          });
        }
        if (avgStability < 50) {
          suggestions.push({
            id: `auto-stab-${platform}-${pillar}`,
            pillar, platform,
            description: `Team stability is critically low (${Math.round(avgStability)}%). Address retention and team composition in ${pillar}.`,
            priority: 'high',
            status: 'open',
            createdBy: 'System',
            isAutoGenerated: true,
          });
        }
      });
    });

    return suggestions;
  }, [teams, selectedQuarter, pillars, relevantPlatforms]);

  const allItems = [...autoSuggestions, ...manualItems];

  const addManualItem = () => {
    if (!newDesc.trim() || !newPillar || !newPlatform) return;
    setManualItems(prev => [...prev, {
      id: `manual-${Date.now()}`,
      pillar: newPillar,
      platform: newPlatform,
      description: newDesc,
      priority: newPriority,
      status: 'open',
      createdBy: 'Manual',
      isAutoGenerated: false,
    }]);
    setNewDesc('');
    setNewPillar('');
    setNewPriority('medium');
    setShowAddForm(false);
  };

  const updateStatus = (id: string, status: ActionItem['status']) => {
    setManualItems(prev => prev.map(item => item.id === id ? { ...item, status } : item));
  };

  const removeItem = (id: string) => {
    setManualItems(prev => prev.filter(item => item.id !== id));
  };

  const priorityColor = (p: string) => p === 'high' ? 'bg-red-100 text-red-800' : p === 'medium' ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800';
  const statusIcon = (s: string) => s === 'done' ? <CheckCircle2 className="w-4 h-4 text-green-500" /> : s === 'in_progress' ? <Clock className="w-4 h-4 text-yellow-500" /> : <AlertTriangle className="w-4 h-4 text-muted-foreground" />;

  return (
    <div className="bg-card rounded-xl p-6 shadow-sm border border-border relative">
      <ChartChatBox chartTitle="Action Items" />
      <div className="flex items-center justify-between mb-1">
        <h3 className="text-base font-semibold text-card-foreground">Action Items for Improvement</h3>
        <Button variant="outline" size="sm" onClick={() => setShowAddForm(!showAddForm)} className="gap-1">
          <Plus className="w-4 h-4" /> Add Item
        </Button>
      </div>
      <p className="text-xs text-muted-foreground mb-4">
        <Lightbulb className="w-3 h-3 inline mr-1" />Auto-generated suggestions based on low scores + your custom action items
      </p>

      {/* Add Form */}
      {showAddForm && (
        <div className="bg-muted/30 rounded-lg p-4 mb-4 space-y-3 animate-fade-in border border-border/50">
          <Input placeholder="Describe the action item..." value={newDesc} onChange={e => setNewDesc(e.target.value)} />
          <div className="flex gap-3 flex-wrap">
            <Select value={newPillar} onValueChange={setNewPillar}>
              <SelectTrigger className="w-[180px] h-8 text-xs"><SelectValue placeholder="Select pillar" /></SelectTrigger>
              <SelectContent>
                {pillars.map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}
              </SelectContent>
            </Select>
            {!platformFilter && (
              <Select value={newPlatform} onValueChange={setNewPlatform}>
                <SelectTrigger className="w-[150px] h-8 text-xs"><SelectValue placeholder="Select platform" /></SelectTrigger>
                <SelectContent>
                  {platforms.map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}
                </SelectContent>
              </Select>
            )}
            <Select value={newPriority} onValueChange={(v) => setNewPriority(v as 'high' | 'medium' | 'low')}>
              <SelectTrigger className="w-[120px] h-8 text-xs"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="low">Low</SelectItem>
              </SelectContent>
            </Select>
            <Button size="sm" onClick={addManualItem} disabled={!newDesc.trim() || !newPillar || !newPlatform}>Save</Button>
          </div>
        </div>
      )}

      {/* Items List */}
      <div className="space-y-2">
        {allItems.length === 0 && (
          <p className="text-sm text-muted-foreground text-center py-6">No action items — all metrics are healthy! 🎉</p>
        )}
        {allItems.map(item => (
          <div key={item.id} className="flex items-start gap-3 border border-border/40 rounded-lg p-3 hover:bg-muted/20 transition-colors">
            {statusIcon(item.status)}
            <div className="flex-1 min-w-0">
              <p className="text-sm text-foreground">{item.description}</p>
              <div className="flex flex-wrap items-center gap-2 mt-1">
                <span className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-medium ${priorityColor(item.priority)}`}>{item.priority}</span>
                <span className="text-[10px] text-muted-foreground">{item.platform} · {item.pillar}</span>
                {item.isAutoGenerated && (
                  <span className="text-[10px] text-primary/70 flex items-center gap-0.5"><Lightbulb className="w-3 h-3" /> Auto</span>
                )}
              </div>
            </div>
            <div className="flex items-center gap-1 shrink-0">
              {!item.isAutoGenerated && (
                <>
                  <Select value={item.status} onValueChange={(v) => updateStatus(item.id, v as ActionItem['status'])}>
                    <SelectTrigger className="w-[100px] h-7 text-[10px]"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="open">Open</SelectItem>
                      <SelectItem value="in_progress">In Progress</SelectItem>
                      <SelectItem value="done">Done</SelectItem>
                    </SelectContent>
                  </Select>
                  <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => removeItem(item.id)}>
                    <Trash2 className="w-3 h-3 text-muted-foreground" />
                  </Button>
                </>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ActionItems;
